### ISSUE TITLE
[Insight] The EntityManager should not be flushed within a loop - in Controller/CorrectionController.php, line 771

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#129]
**[in Controller/CorrectionController.php, line 771](https://github.com/InnovaLangues/CollecticielBundle/blob/8c355cf48199aabd474f2a404b613673f89d9b64/Controller/CorrectionController.php#L771)**

> Calling `flush` is a resource intensive operation, especially when a lot of entities are managed by Doctrine. You should pass the entity you want to flush as parameter, or avoid flushing inside a loop.

```php
                        $event = new LogCommentReadCreateEvent($dropzone, $dropzoneChangeSet, $comment_read_add);

                        $this->dispatch($event);
                    }
                }
                $em->flush();
                // Fin ajout.
            }    
        }


```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/a50e7885-90fe-4adc-ba8a-695c8def1b86/analyses/14)_

**Comment by purplefish32** [comment]
This issue was moved to claroline/ClaroSupport#16
