### ISSUE TITLE
[Insight] Unused method, property, variable or parameter - in Controller/CorrectionController.php, line 712

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#131]
**[in Controller/CorrectionController.php, line 712](https://github.com/InnovaLangues/CollecticielBundle/blob/8c355cf48199aabd474f2a404b613673f89d9b64/Controller/CorrectionController.php#L712)**

> This `countCorrection` local variable is declared but never used. You should remove it.

```php
        $correction = $this
            ->getDoctrine()
            ->getRepository('InnovaCollecticielBundle:Correction')
            ->getCorrectionAndDropAndUserAndDocuments($dropzone, $correctionId);

        $countCorrection = count($correction);

        // Parcours des documents sélectionnés
        foreach ($correction->getDrop()->getDocuments() as $document) {
            if ($document->getId() == $documentOri->getId())
            {
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/a50e7885-90fe-4adc-ba8a-695c8def1b86/analyses/14)_

**Comment by purplefish32** [comment]
This issue was moved to claroline/ClaroSupport#14
