### ISSUE TITLE
Classement des colonnes

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#149]
Les dates ne sont pas classées correctement (collonne "En date du)
En effet actuellement, lorsqu'on classe par date, on observe par exemple ceci :
01-11-2015
02-11-2015
03-11-2015
12-10-2015
17-10-2015
au lieu de ceci :
12-10-2015
17-10-2015
01-11-2015
02-11-2015
03-11-2015

**Comment by purplefish32** [comment]
This issue was moved to claroline/Claroline#761
