### ISSUE TITLE
Ajout de la gestion "Evaluation"

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#157]
Une évaluation est : 
soit par notation avec 20 par défaut
soit par appréciation avec "-" par défaut

**Comment by ericvincenterv** [comment]
Début de travail ici : 
https://github.com/InnovaLangues/CollecticielBundle/commit/4304e32137293b6e5af13438e9d5d6b9f7ed6b23

**Comment by purplefish32** [comment]
This issue was moved to claroline/Claroline#758
