### ISSUE TITLE
Correction clic sur boutons d'un onglet

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#20]
Lors du clic sur "Demandes adressées", nous arrivons sur les critères et lors d'un nouveau clic sur l'onglet, nous arrivons sur le bon écran : "Travaux terminés en attente de correction(s)"

**Comment by eldoniel** [comment]
Corrected in branch : https://github.com/InnovaLangues/CollecticielBundle/tree/20-Correction_clic_sur_bouton_d_onglet
