### ISSUE TITLE
Modifier le message de fermeture

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#220]
En cas de fermeture, modifié le texte (sous fond jaune) « Ce collecticiel
n'est pas encore ouvert » par « Ce collecticiel est fermé. Il n’est pas
possible d’y déposer des documents », en caractères de taille plus petite
qu’actuellement (sinon, cela prendrait trop de place)

Demande de JJQ du 02/02/2016.

**Comment by ericvincenterv** [comment]
A voir car il y aurait peut-être confusion entre les messages suivant si on est ENSEIGNANT ou ELEVE.

Voir avec JJQ.

**Comment by ericvincenterv** [comment]
JJQ va réfléchir, ne rien toucher pour l'instant.

**Comment by jj-quintin** [comment]
Bon, dans cette version (on verra plus tard si c'est assez clair pour les utilisateurs), indiquer dans tous les cas (étudiants et enseignants) 

> Ce collecticiel est fermé
