### ISSUE TITLE
Aligner check-box en-tête sur check-box des cellules

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#228]
Aligner check-box en-tête sur check-box des cellules

Onglet : demandes adressées

**Comment by jj-quintin** [comment]
En réalité, c'est valable pour toutes les en-têtes des tableau : soigner la centration des en-têtes sur les éléments des cellules lorsque ceux-ci sont eux-mêmes centrés en largeur. Dans l'image ci-dessous, il s'agit des deux dernières colonnes de droite (transmettre une demande... et Commentaire)

![icone-demande-commentaire-ou-evaluation](https://cloud.githubusercontent.com/assets/16414632/12911231/3249caa6-cf11-11e5-89cb-a2fb9e15d929.png)
