### ISSUE TITLE
Colonne "demande de commentaire"

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#231]
Changer l’icône en-tête colonne « Demande de commentaire » par ??? (ticket en attendant)
Y adjoindre une info-bulle avec le texte « Demande de commentaire »

Onglet : "demandes adressées"

**Comment by ericvincenterv** [comment]
Attente de la font-awesome à afficher pour clore cette issue.

**Comment by jj-quintin** [comment]
C'est la même que dans l'espace collecticiel des étudiants, à savoir la flèche noire


![icone-demande-commentaire-ou-evaluation](https://cloud.githubusercontent.com/assets/16414632/12911043/d92427ce-cf0f-11e5-8564-1a411340f7dd.png)

Précision : dans le cas où l'évaluation a été sélectionnée dans paramètres

- Même icône
- Mais l'info-bulle est "Transmettre une demande d'évaluation"

Et donc, dans le cas où l'évaluation n'a pas été sélectionnée dans paramètre

- Même icône
- Mais l'info-bulle est "Transmettre une demande de commentaire"

**Comment by ericvincenterv** [comment]
Fait.

Dans notre cas actuel, on gère le cas où l'évaluation n'a pas été sélectionnée dans l'onglet "Paramètres"

**Comment by jj-quintin** [comment]
Je préférerais ne pas le fermer car il sera valable pour la suite. Simplement changer le Milestone ne suffirait-il pas ? Sinon, risque de l'oublier et puis, je dois à nouveau le rédiger. Tu comprends ?

**Comment by ericvincenterv** [comment]
Oui, je m'étais fait la remarque.

**Comment by ericvincenterv** [comment]
Ticket fermé concernant l'accusé de réception.

Pour l'évaluation, j'ai créé ce ticket : 
https://github.com/InnovaLangues/CollecticielBundle/issues/256
