### ISSUE TITLE
Menu Actions (affichage)

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#234]
Modifier le menu déroulant "Actions" pour le rendre conforme aux autres menus de ce type sur la plateforme. Voir les deux images ci-dessous (détails bouton Actions = les 4 coins sont arrondis ;  ajouter petite flèche bas indiquant que c'est un menu déroulant ; sortir le bouton du tableau et l'aligner sur la colonne avec les check-box...)

![menu-actions-1](https://cloud.githubusercontent.com/assets/16414632/12911701/93344f64-cf14-11e5-9b32-24d9a9f1e9a4.png)

![menu-actions-2](https://cloud.githubusercontent.com/assets/16414632/12911703/9880fae4-cf14-11e5-933f-61b1c3ce6454.png)

**Comment by ericvincenterv** [comment]
Le résultat obtenu : 
![bouton-action](https://cloud.githubusercontent.com/assets/5363344/12912738/d5f722b2-cf1a-11e5-880f-6da4cf89bc1d.png)

**Comment by jj-quintin** [comment]
ok mais je dois vérifier si, ailleurs dans la platefiorme, "Actions" est au pluriel

**Comment by jj-quintin** [comment]
Actions au pluriel, avec s donc

**Comment by ericvincenterv** [comment]
Fait.
