### ISSUE TITLE
Texte alerte demande de commentaire ou d'évaluation

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#236]
Lorsqu'on transmet une demande d'évaluation ou de commentaire, on obtient l'alerte suivante : 

Titre de l'alerte : Communication d'une demande (de commentaire, d'évaluation)
Texte de l'alerte : Voulez-vous transmettre une demande de commentaire ou d'évaluation pour ce document ?

C'est l'ancienne version. Maintenant on sait si la demande concerne un simple commentaire ou une demande d’évaluation (évaluation sélectionnée dans paramètres => version évaluation ; non sélectionné => version commentaire

**Le titre et le contenu peuvent être adaptés en conséquences** : 

_Version commentaire_ : 

Titre de l'alerte : Communication d'une demande de commentaire
Texte de l'alerte : Voulez-vous transmettre une demande de commentaire pour ce document ?

_Version évaluation_: 

Titre de l'alerte : Communication d'une demande d'évaluation
Texte de l'alerte : Voulez-vous transmettre une demande d'évaluation pour ce document ?

**Comment by ericvincenterv** [comment]
Fait.
