### ISSUE TITLE
Annuler une demande de commentaire ou d'évaluation : Ajout alerte (confirmation)

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#237]
Ajouter une fenêtre d'alerte/confirmation lorsque que l'utilisateur veut annuler une demande. 

Même type d'alerte que celle utilisée pour confirmer l'envoi d'une demande

_Version Commentaire_

Titre : Annuler la demande de commentaire
Texte : Voulez-vous annuler votre demande de commentaire ?

_Version évaluation _

Titre : Annuler la demande d'évaluation
Texte : Voulez-vous annuler votre demande d'évaluation ?

**Comment by ericvincenterv** [comment]
Voir avec Donovan si nous ajoutons ce ticket dans la prochaine version prévue la semaine prochaine ou dans la suivante ?

**Comment by jj-quintin** [comment]
Comme vous voulez. Dis-moi ici ce que vous décidez

**Comment by ericvincenterv** [comment]
Ajout dans la version qui suivra celle de mardi.

**Comment by ericvincenterv** [comment]
@jj-quintin : tu as écrit : "Ajouter une fenêtre d'alerte/confirmation lorsque que l'utilisateur veut annuler une demande. "

Question : est-ce que j'ajoute cette fenêtre quand c'est l'**enseignant** que veut annuler une demande ?

**Comment by jj-quintin** [comment]
Non, quiconque
Pour info, quand j'utilise le terme "utilisateur" on dira que c'est pour tout le monde, enseignant et étudiant, ok ?

**Comment by ericvincenterv** [comment]
Donc, si le terme "utilisateur" englobe notamment l'enseignant, il faut ajouter une fenêtre d'alerte/confirmation lorsque que l'utilisateur veut annuler une demande. Non ?

**Comment by jj-quintin** [comment]
Oui, lorsqu'un utilisateur, quel qu'il soit, enseignant ou étudiant, veut annuler une demande, une fenêtre d'avertissement lui demande de confirmer. Je ne pense d'ailleurs pas t'avoir donner le texte. Si ?

**Comment by ericvincenterv** [comment]
OK.
Pour les textes, tu les as précisé au tout début de ce ticket.

**Comment by ericvincenterv** [comment]
En fait, il y a les textes côté **élève**, pas du côté **enseignant**.
En tout cas, la fenêtre a été ajoutée.

**Comment by jj-quintin** [comment]
C'est valable pour un "utilisateur", donc n'importe qui (y compris l'enseignant), mais de ce fait le texte suivant convient mieux (le "votre" a été remplacé par "cette")

Même type d'alerte que celle utilisée pour confirmer l'envoi d'une demande

Version Commentaire

Titre : Annuler la demande de commentaire
Texte : Voulez-vous annuler cette demande de commentaire ?

Version évaluation

Titre : Annuler la demande d'évaluation
Texte : Voulez-vous annuler cette demande d'évaluation ?

**Comment by ericvincenterv** [comment]
![Uploading Capture d'écran - 01032016 - 16:42:37.png…]()

**Comment by ericvincenterv** [comment]
![capture d ecran - 01032016 - 16 42 37](https://cloud.githubusercontent.com/assets/5363344/13432144/bae4e8de-dfcc-11e5-89e2-b8557b097de2.png)
