### ISSUE TITLE
Suppression d'un document : Modification titre/texte alerte (confirmation)

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#238]
_Actuellement _

Titre : Supprimer un document
Texte : Êtes-vous sûr de vouloir supprimer ce document ?

Demande changement par : 

Titre : Suppression d'un document
Texte : Voulez-vous supprimer ce document ?

**Comment by ericvincenterv** [comment]
Compris et fait.
