### ISSUE TITLE
Accusé de réception enseignant : réversibilité

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#240]
L'enseignant qui, par erreur par exemple, fixe une valeur de réception pour un document doit pouvoir la changer. Il doit doit pouvoir cliquer sur la main par exemple, obtenir la liste des valeurs des accusés de réception et changer de valeur

**Comment by ericvincenterv** [comment]
La modification d'un accusé de réception est possible mais en passant par la liste dans le bouton "Actions".

J'ajoute donc cette possibilité au niveau de la **colonne** également.
