### ISSUE TITLE
Accusé de réception étudiant : réception d'un accusé => ne pas permettre l'annulation de la demande

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#241]
Lorsque l'étudiant a reçu un accusé de réception (que la valeur soit : Document bien reçu, Document illisible, Document incomplet, Erreur de document, Doublon), il ne peut plus annuler la demande (ni supprimer le document bien entendu)

**Comment by ericvincenterv** [comment]
Ce ticket se rapproche de celui-ci : https://github.com/InnovaLangues/CollecticielBundle/issues/247

**Comment by jj-quintin** [comment]
Je vais donc allé voir le #247

**Comment by jj-quintin** [comment]
Ok, on reporte donc ce ticket sur le #247
