### ISSUE TITLE
Accusé de réception enseignant : dysfonctionnement si "Pas d'accusé de réception"

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#242]
Si, en tant qu'enseignant, je choisis pour un document, la valeur "Pas d'accusé de réception", le système d'affichage des icônes d'accusé de réception pour les opérations suivantes d'accusé de réception dysfonctionne = il affiche toujours, dans la cellule, le bouton d'accusé de réception (main bleue) après avoir indiqué une valeur d'accusé.

Détail : 

Document 1
1. Je clique sur la main et j'indique la valeur "Pas d'accusé de réception"
2. L'affichage de ce document reste sur la main bleue (c'est correct)

Document 1 tjs
1. Je clique à nouveau sur la main bleue pour indiquer Document bien reçu
2.  L'affichage de ce document reste sur la main bleue (ce n'est pas correct, l'icône devrait être actualisée

et puis, cela débloque : 

Document 2 et autre = indiquer une valeur d'accusé n’actualise plus l'icône, cela reste tjs sur la main bleue

Par contre le nombre d'opération change et l'étudiant voit bien les bonnes icônes

**Comment by ericvincenterv** [comment]
Je viens de tester en démo-v6. Je n'ai pas réussi à reproduire.

**Comment by jj-quintin** [comment]
inscris-moi dans l'espace d'activités du TestAR2 en tant que gestionnaire si tu veux bien que j'y fasse mes tests

**Comment by ericvincenterv** [comment]
Je viens de le faire.

**Comment by jj-quintin** [comment]
Je ne parviens pas à le reproduire mais je t'ai inscrit à l'espace où se trouve le collectiel qui bugge et le bug est tjs là (Espace personneljjq (jjq)   Ressources   Test Janvier-Février 2016 Collectiel    Test Collecticiel). Tu pourras le voir : 

- dans le collecticiel "Test Collecticiel"
- Onglet Demandea adressées
- Essaie d'indiquer la valeur "Document bien reçu" au document Titre 1 (chez moi ça ne marche pas)

**Comment by ericvincenterv** [comment]
Je me suis connecté et j'obtiens ceci : 

![capture d ecran - 09022016 - 14 54 23](https://cloud.githubusercontent.com/assets/5363344/12918014/0d9bf612-cf3d-11e5-9a19-5dcdde95b8d2.png)

Le document "titre 1" est actualisé en niveau "accusé de réception".

**Comment by jj-quintin** [comment]
zut, moi pas : 

![accuse de reception-dysfonctionnement-suite](https://cloud.githubusercontent.com/assets/16414632/12918276/a01b56b2-cf3e-11e5-82b9-68a51e7b3af5.png)

**Comment by jj-quintin** [comment]
Ah ! D'après ton image, y'a aussi un problème au niveau des icônes des trois premiers : tu as des  mains bleues alors que tu devrais avoir ce que j'ai moi

**Comment by jj-quintin** [comment]
Attention, les accusés de réception sont liés au document (nous devrions voir la même chose ainsi que les étudiants pour un même document) alors que les "+ x" des commentaires sont liés à l'utilisateur, ok ?

**Comment by ericvincenterv** [comment]
Oui pour : 
````
Un accusé de réception est lié à un document
Un commentaire est lié à un utilisateur
````

Je regarde pourquoi nous n'avons pas les mêmes résultats.

**Comment by ericvincenterv** [comment]
Je viens de reproduire également de mon côté avec mon jeu de test.

**Comment by jj-quintin** [comment]
ok

**Comment by ericvincenterv** [comment]
Corrigé.
