### ISSUE TITLE
Accusé de réception enseignant : décompte des opérations en attente ("!")

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#243]
Dysfonctionnement : le compteur de opérations en attente (le !) ne devrait pas tenir compte du choix de la valeur "Pas d'accusé de réception". Actuellement il décompte de 1 après le choix de cette valeur

Précisions la valeur "Pas d'accusé de réception" sert surtout à remettre la valeur par défaut lors d'une correction d'une valeur indiquée par erreur (réversibilité)

**Comment by jj-quintin** [comment]
Je t'ai inscrit (eric	vincent	eric	eirc.vincent@u-grenoble3.fr) là où j'ai rencontré le bug (http://demo-v6.innovalangues.net/innovacollecticielbundle/18/drops/awaiting dans  Espace personneljjq (jjq)   Ressources   Test Janvier-Février 2016 Collectiel    Test Collecticiel)

Car effectivement je ne parviens pas à reproduire le bug ailleurs, mais dans ce collecticiel là il y est bien et je pense que tu pourras le voir (onglet Demandes adressées : essaie d'indiquer un accusé de réception à Titre 1 par exemple)

**Comment by ericvincenterv** [comment]
A rapprocher de ce ticket : https://github.com/InnovaLangues/CollecticielBundle/issues/206

Pour moi, le nombre à afficher = le nombre de résultat en attente = nombre de documents déposés par tous les étudiants inscrits au collecticiel qui n'ont pas encore un accusé de réception.

![capture d ecran - 09022016 - 15 19 14](https://cloud.githubusercontent.com/assets/5363344/12918685/82f450be-cf40-11e5-8c8f-6e712c9b39fb.png)

Dans le cas de ce collecticiel, le compteur affiché sera "2".

**Comment by jj-quintin** [comment]
Suite : 
Le compteur doit également tenir compte des actions qui entraîne une réversibilité

Soit le cas suivant pour la colonne des accusé&s de réception : 
1) Je reçois au total 10 demandes => ! = 10 opérations en attente
2) J'effectue 10 accusés de réception de la valeur est différente de "Pas d'accusé de réception" => le "!" disparaît
3) Je sélectionne tous les documents et je choisis la valeur "Pas d'accusé de réception" => je reviens en arrière, je remets les valeurs à leur état de départ =W "!" = 10 opérations en attentes

**Comment by jj-quintin** [comment]
Pour reprendre ton exemple (image) : oui le nombre d'opérations en attente est bien égal ici à 2, ce qui ne fonctionne pas ainsi dans le cas où je choisis la valeur "Pas d'accusé de réception"

**Comment by jj-quintin** [comment]
Comme ici : 
![dysfonctionnement-decompte](https://cloud.githubusercontent.com/assets/16414632/12918884/e32272d0-cf41-11e5-9c14-90dac4843a16.png)

**Comment by ericvincenterv** [comment]
OK, reproduit en local chez moi.
A faire (note pour moi) : exclure les documents qui ont un AR à zéero en plus de ceux qui n'ont pas d'AR du tout.

**Comment by ericvincenterv** [comment]
Fait avec ce ticket : 
https://github.com/InnovaLangues/CollecticielBundle/issues/240
