### ISSUE TITLE
Ajouter un document - rédiger un texte

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#244]
- Modifier _Votre texte ici_ par :  _Titre du document_
- Placer un texte similaire dans le champ du corps de texte : _Votre texte ici_
- Les deux étant obligatoires, actuellement seul le titre fait l'objet d'un renseignement par l'info bulle "Veuillez renseigner ce champ" : le faire pour les deux
- Supprimer le point à la fin de _Veuillez renseigner ce champ_

![rediger un texte](https://cloud.githubusercontent.com/assets/16414632/12918168/e6613ade-cf3d-11e5-946f-93bbc45ff689.png)

**Comment by ericvincenterv** [comment]
Les 2 premières demandes sont faites.

**Comment by ericvincenterv** [comment]
@jj-quintin : est-il possible de couper ce ticket en 2 parties en mettant les 2 premières demandes dans un ticket (demandes faites) et les 2 autres demandes qui nécessitent un traitemet spécial dans un autre ticket ?
Si oui, je le fais.

**Comment by jj-quintin** [comment]
oui, ok, bien sûr, pas de souci

**Comment by ericvincenterv** [comment]
Je m'en occupe.

**Comment by ericvincenterv** [comment]
Ticket coupé en 2, voir les références des nouveaux tickets ci-dessus.

**Comment by ericvincenterv** [comment]
Voir ce lien pourrait être utile : http://stackoverflow.com/questions/5478800/override-css-for-html5-form-validation-required-popup (merci @arnaudbey )
