### ISSUE TITLE
Bug : Menu Actions Accusé de réception sans sélection

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#245]
Menu actions accusé de réception avec l'un des deux cas suivants :+1: 
- **pas de fichier sélectionné** suivi menu actions, accusé de réception, puis de la sélection d'une valeur puis ok
- ou un fichier au moins sélectionné, suivi de menu actions, accusé de réception, p**as de valeur sélectionnée** et ok 

Entraîne bug "En attente", cf image, sans possibilité de se dégager de cette situation (obligation de fermer l'onglet

![bug-menu-actions](https://cloud.githubusercontent.com/assets/16414632/12919153/09860602-cf43-11e5-883a-7f123ab55eb8.png)

**Comment by jj-quintin** [comment]
Proposition d’améliorations : 
 
1) Pas de fichier sélectionné => options du menu Actions sont grisées et inactives
2) Fenêtre modale des valeurs d'accusé de réception : tant qu'une valeur n'est pas sélectionnée => le bouton ok est inactivable

**Comment by ericvincenterv** [comment]
Compris et fait.
