### ISSUE TITLE
Annuler une demande côté étudiant après accusé de réception

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#247]
Il ne devrait plus être possible pour l'étudiant d'annuler une demande après réception d'un accusé de réception (dont la valeur n'est pas "Pas d'accusé de réception" bien sûr)

Dans ce cas, la possibilité d'annuler une demande est conditionné au respect de 2 (deux pour l'instant, dans l'attente du développement de l'évaluation) conditions : 

- pas de commentaire déposé par l'enseignant
ET
- pas d'accusé de réception reçu (accusé de réception dont la valeur est différente de "Pas d'accusé de réception")

Attention à la réversibilité de l'accusé de réception

Pour illustration, ce cas : 

1) L'enseignant envoie un accusé de réception = à "Document bien" et n'a déposé aucun commentaire
=> L'annulation de la demande par l'étudiant n'est pas possible (afficher verrou)

2) L’enseignant décide par la suite de remettre la valeur de l'accusé de réception à "Pas d'accusé de réception" (réversibilité) tout en ne déposant tjs pas de commentaire
=> L'annulation de la demande est maintenant possible du côté de l'étudiant (afficher bouton annuler)

**Comment by ericvincenterv** [comment]
La première partie est maintenant faite. Je vais m'occuper de la réversibilité de l'accusé de réception.

**Comment by jj-quintin** [comment]
ok

**Comment by ericvincenterv** [comment]
Est-ce que la gestion côté **enseignant** change ?
Je peux dire par là : 
est-ce que si le document a un AR (autre que "Pas d'accusé de réception), j'affiche également un verrou ?
est-ce que si le document a un commentaire d'un enseignant, j'affiche également un verrou ?

**Comment by jj-quintin** [comment]
Si j'ai bien compris la question, la réponse est oui.

Le cas suivant : 
Je suis enseignant
Je transmets un  AR à un étudiant X ou dépose un commentaire, pour le document qui fait l'objet de cette demande
=> La possibilité d'annuler la demande **de ce document** par X ou par quiconque (dont l'enseignant) est bloquée

La logique est donc une logique de document pas d'utlisateur
