### ISSUE TITLE
Infobulles Onglets Demandes adressées

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#248]
Info-bulles manquantes sur : 

Version enseignant - Onglet demandes adressées
- Icône entête de la colonne des demandes de commentaires, texte "Demande de commentaire"
- Icône entête de la colonne Accusé de réception, texte "Accusé de réception"
- Check-box entête de la colonne de sélection, texte "Tout sélectionner"

Modification du texte des infos-bulles des cellules de la colonne des demandes de commentaire

Modifier les info-bulles associées au V (actuellement « Demande traitée) et au - (Demande non traitée) par « Document commenté » (V) et « Document non commenté » (-)

**Comment by ericvincenterv** [comment]
A vérifier mais je pense que tout ceci a été fait.

**Comment by ericvincenterv** [comment]
Fait.
