### ISSUE TITLE
Paramètres : "Ce formulaire ne doit pas contenir des champs supplémentaires"

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#249]
Supprimer le message « Ce formulaire ne doit pas contenir des champs supplémentaires » qui apparaît après la sauvegarde des paramètres

**Comment by ericvincenterv** [comment]
A rapprocher de ce ticket : 
https://github.com/InnovaLangues/CollecticielBundle/issues/221
