### ISSUE TITLE
Ouverture après création d'un nouveau collecticiel : par défaut ouvert

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#250]
Dans Paramètres, le radio button Ouvert est sélectionné par défaut

**Comment by ericvincenterv** [comment]
A rapprocher de ce ticket : 
https://github.com/InnovaLangues/CollecticielBundle/issues/218

**Comment by jj-quintin** [comment]
ok, à supprimer donc
