### ISSUE TITLE
Erreur annuler demande et demande traitée

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#251]
Après une demande transmise par l'étudiant 
Lorsque l'étudiant a déposé lui-même un commentaire et que l’enseignant n'a rien déposé du tout
Le système réagit comme si c'était l’enseignant qui avait traité la demande (déposé un commentaire)

Il faut distinguer ce qui revient à l'auteur de la demande et ce qui revient au destinataire de la demande. Ne pas se baser uniquement sur la présence ou non de commentaire. 

J'entrerai dans les détails des règles à appliquer si tu le demandes

Voici les saisies d'écran qui illustrent ce qui se passe actuellement en pareille situation : 

Situation côté étudiant : 

![erreur-annuler-demande](https://cloud.githubusercontent.com/assets/16414632/12921132/0246de80-cf4c-11e5-9c8b-1ada4b9a804e.png)

Or c'est le commentaire que l’étudiant lui-même (l'auteur de la demande) a déposé (pas l’enseignant, le destinataire de la demande) : 

![commentaire-etu1](https://cloud.githubusercontent.com/assets/16414632/12921175/321f9322-cf4c-11e5-80ea-21159d168c2c.png)

Même erreur côté enseignant : la demande est considérée comme traitée alors que l'enseignant n'a pas déposé de commentaire : 
 
![erreur-annuler-demande-enseignant](https://cloud.githubusercontent.com/assets/16414632/12921194/4f7fb636-cf4c-11e5-90a6-4db301478a3d.png)

**Comment by ericvincenterv** [comment]
En fait, quand un étudiant dépose un commentaire en étant étudiant, je pense que tout est OK.

Par contre, dans ton cas, si j'ai bien compris, tu as déposé un commentaire dans un espace d'un étudiant en étant enseignant.

**Comment by jj-quintin** [comment]
Ah oui, bien vu ! Je testerai une vraie connexion étudiant demain si j'ai le temps pour être certain que tout est ok de ce côté

**Comment by ericvincenterv** [comment]
OK, à suivre

**Comment by jj-quintin** [comment]
Cela se confirme. Dans tous les cas, la demande est considérée comme traitée (V côté enseignant) lorsque l'étudiant dépose lui-même un commentaire. je me suis connecté comme etu1 et : 

- j'ai d'abord commenté, puis transféré une demande
- j'ai d'abord communiqué une demande, puis commenté

Je me suis déconnecté puis reconnecté comme enseignant et dans les deux cas j'ai un V (demande traitée) pour ces deux documents

**Comment by ericvincenterv** [comment]
Je résume : 
une demande adressée doit être en statut "Document commenté" et non plus "Document non commenté" lorsque c'est l'enseignant qui a commenté.

Si un étudiant a déposé 10 commentaires sur son document alors dans l'espace enseignant, cette demande sera avec le statut "Document non commenté".

Est-ce correct ?

**Comment by jj-quintin** [comment]
Oui, mais je réalise du coup que le texte que l'enseignement va lire sous le - de sa colonne Demande adressées ("Document non commenté") est absurde. je vais devoir t'en proposer (encore :-/) un autre

**En synthèse** : 

**Oui pour** : tant que celui à qui on a adressé la demande (l’enseignant ici) n'a pas lui-même déposé un commentaire en relation avec le doc en question, l'état du doc reste sur "-" (il passe donc à "V" quand il aura déposé lui-même un commentaire) Ok ?

**Non pour** le texte de l'info-bulle que j'ai proposé de modifier (qui apparaît du coup comme un non sens). Je vais devoir en proposer un autre (en réalité deux autres : 1 pour "-" et 1 pour "V")

**Comment by ericvincenterv** [comment]
Compris.
A faire pour le "Oui pour"
En attente pour le "Non pour".

**Comment by ericvincenterv** [comment]
Première partie : faite.
En attente de la 2ème partie pour la livraison de mardi.
Sinon, couper ce ticket en 2 et affecter la partie qui reste à faire à la prochaine version.

**Comment by ericvincenterv** [comment]
Voir : https://github.com/InnovaLangues/CollecticielBundle/issues/257
