### ISSUE TITLE
Suppression et mises à jour des accusés de réception ?

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#254]
@jj-quintin :
Nous avons vu qu'il faut supprimer l'accusé de réception d'un document lorsque l'enseignant émet un nouvel accusé de réception pour le document en question.

Par contre, dans la configuration actuelle, un autre enseignant peut très bien également émettre un accusé de réception pour le même document.

Actuellement, quand un enseignant change SON accusé de réception pour un document "A", je supprime SON ancien accusé puis j'insère le nouveau.

Question : 
faut-il dès maintenant prendre en compte le fait qu'un enseignant pourra changer l'accusé de réception d'un autre enseignant sur un même document ?
Pour un document, est-ce que c'est toujours le dernier AR qui fait foi quelque soit l'enseignant ?

**Comment by jj-quintin** [comment]
On va faire simple pour l'instant et on verra comment ça marche (c'est le moins risqué en temps de développement) quite à évoluer par la suite

Donc, la règle sera (pour l'instant) : c'est le dernier changement qui prévaut et qui écrase/supprime le précédent, quelque soit l'auteur du changement (l'enseignant).

C'est absurde mais techniquement (et pour l'instant), un enseignant B peut modifier l'AR Document bien reçu communiquer par l’enseignant A en Document illisible 

et l'étudiant après avoir été soulagé d'apprendre que son document a bien été reçu, sera affreusement surpris d'apprendre que son document est maintenant refusé. A ce stade on table sur l'intelligence des enseignants 

On aura la même question pour les évaluations

Ce qui serait bien, c'est de voir, dans une info-bulle qui a édité l'AR
Ce qui serait également valable pour l'évaluation
Voire pour la demande traitée (V)

A discuter

**Comment by ericvincenterv** [comment]
1/ Fait.

2/Sutie et fin sur ce ticket : https://github.com/InnovaLangues/CollecticielBundle/issues/255
