### ISSUE TITLE
Infobulle AR : qui a fait quoi ?

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#255]
Suite à ce ticket : 
https://github.com/InnovaLangues/CollecticielBundle/issues/254

prévoir ceci : 
"
On aura la même question pour les évaluations

Ce qui serait bien, c'est de voir, dans une info-bulle qui a édité l'AR
Ce qui serait également valable pour l'évaluation
Voire pour la demande traitée (V)

A discuter
"

**Comment by ericvincenterv** [comment]
@jj-quintin : 
l'idée serait donc de positionner le nom de l'enseignant qui a fait l'action (AR ou évaluation ou demande traitée) , c'est bien ça ?
si oui, prévoit-on ceci dès la prochaine version ?

**Comment by jj-quintin** [comment]
C'est l'idée oui. Dans l'exemple que j'avais pris lundi, Donovan et moi sommes enseignants du même collecticiel. Nous recevons une demande de commentaire/d'évaluation. Donovan y répond (il dépose un commentaire dans la version commentaire ou transmet une évaluation dans la version évaluation). On voit (il voit et je vois) en plaçant le curseur sur le V que c'est lui qui a traité la demande (X a ...). Ce qui, soit dit en passant permet d'avancer sur le ticket qui porte sur les textes de ces info-bulles ;-)

Si la prochaine version porte sur l'évaluation (ce qui serait bien) alors on peut l'envisager en même temps que l'évaluation, ce serait bien, oui

**Comment by ericvincenterv** [comment]
A rapprocher du ticket : https://github.com/InnovaLangues/CollecticielBundle/issues/257
