### ISSUE TITLE
Evaluation : modification des info-bulles

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#256]
Des messages sont à modifier lorsque le choix "évaluation" a été choisi.

Voir les explications sur ce ticket : 
https://github.com/InnovaLangues/CollecticielBundle/issues/231

**Comment by ericvincenterv** [comment]
@jj-quintin : 
question : 
à terme, il sera possible que l'enseignant sélectionne dans les paramètres le choix "Accusé de réception" ET "Evaluation".
Dans ce cas, quel est le message à afficher et comment gère-t-on cette colonne ?

**Comment by jj-quintin** [comment]
Oui, c'est le but. Dans la plupart des cas, l'accusé de réception permet de faire patienter l'étudiant en attente de l'évaluation. Donc l'accusé de réception sera rarement seul, et quasiment tjs associé à l'évaluation. 

Ceci est géré comme suit

Quand l'évaluation est sélectionnée, l'étudiant qui fait une demande, fait en réalité une demande d'**évaluation**

Quand l'évaluation n'est pas sélectionnée, l'étudiant qui fait une demande, fait en réalité une demande de **commentaire**

Corollaires, côté enseignant : 

Quand l'évaluation est sélectionnée, la demande est traitée lorsque l'enseignant a transmis l'évaluation (vérifier si cette colonne apparaît, je ne sais plus)

Quand l'évaluation n'est pas sélectionnée, la demande est traitée lorsque l'enseignant a déposé un commentaire

**Comment by ericvincenterv** [comment]
Oui, 2 colonnes s'affichent lorsque l'évaluation est sélectionnée mais le traitement n'est pas encore en plus : 

![capture d ecran - 18022016 - 13 47 41](https://cloud.githubusercontent.com/assets/5363344/13143729/37f2104e-d646-11e5-93ba-ce121c37ec10.png)
