### ISSUE TITLE
Terminer "Annuler demande"

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#257]
Voir la partie 2 de ce ticket : 
https://github.com/InnovaLangues/CollecticielBundle/issues/251

**Comment by ericvincenterv** [comment]
@jj-quintin : 
"
Non pour le texte de l'info-bulle que j'ai proposé de modifier (qui apparaît du coup comme un non sens). Je vais devoir en proposer un autre (en réalité deux autres : 1 pour "-" et 1 pour "V")"

**Comment by jj-quintin** [comment]
Clore le ticket, je n'ai pas mieux pour l'instant que les actuels. Donc on laisse les anciens ainsi et on verra à l'avenir

**Comment by jj-quintin** [comment]
Je parle des textes des 2 info-bulle qui correspondent à "-" et "V" ok ?

**Comment by jj-quintin** [comment]
Voir ticket 255, peut-être pas clos tout compte faite, dans ce cas, fusionner les deux tickets ?

Mon commentaire ticket 255 : 
"C'est l'idée oui. Dans l'exemple que j'avais pris lundi, Donovan et moi sommes enseignants du même collecticiel. Nous recevons une demande de commentaire/d'évaluation. Donovan y répond (il dépose un commentaire dans la version commentaire ou transmet une évaluation dans la version évaluation). On voit (il voit et je vois) en plaçant le curseur sur le V que c'est lui qui a traité la demande (X a ...). Ce qui, soit dit en passant permet d'avancer sur le ticket qui porte sur les textes de ces info-bulles ;-)"

**Comment by ericvincenterv** [comment]
Il faut donc positionner en tooltip sur le "V" un message de type "X a traité la demande" ?

X sera donc le premier enseignant qui aura déposé un commentaire pour cette demande (dans la version commentaire), c'est bien ça ?

**Comment by jj-quintin** [comment]
Il faut donc positionner en tooltip sur le "V" un message de type "X a traité la demande" ?

Si c'est possible, oui

Dons, les deux textes des tooltip seraient : 

- V : "X a traité cette demande" (où X = Prénom Nom ?)
- - : "Demande non traitée" (revenir donc à l'ancienne version :-/)

**Comment by ericvincenterv** [comment]
Partons sur "Prénom Nom".

**Comment by jj-quintin** [comment]
ok
