### ISSUE TITLE
Demande automatiquement transmise

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#267]
A relier à un ancien ticket (de mémoire)

Si, en tant qu’enseignant, je dépose un fichier dans mon collecticiel ou dans le collecticiel partagé, la demande est transmise automatiquement dès l'ajout du document (voir image ci-dessous)

![image](https://cloud.githubusercontent.com/assets/16414632/13117475/61ece2bc-d5a0-11e5-98e2-6a893d46d812.png)

**Comment by ericvincenterv** [comment]
Quand un enseignant dépose un document, sa demande est automatiquement transmise dès l'ajout du document.

Ce que je viens de faire : 

_Dépôt de 2 documents_
![capture d ecran - 18022016 - 13 34 53](https://cloud.githubusercontent.com/assets/5363344/13143477/82e7f5b6-d644-11e5-93b2-4ceac0f4ee96.png)

_Je vois les 2 documents dans les espaces partagés_
![capture d ecran - 18022016 - 13 35 08](https://cloud.githubusercontent.com/assets/5363344/13143486/8e868aa4-d644-11e5-89aa-d833ee2cdbc3.png)

_Et je vois les 2 documents dans la liste des demandes adressées_
![capture d ecran - 18022016 - 13 35 21](https://cloud.githubusercontent.com/assets/5363344/13143497/9bd34bac-d644-11e5-9c0a-7cfd78b7d200.png)

Peux-tu me préciser le dysfonctionnement ?

**Comment by jj-quintin** [comment]
C'est le problème déjà signalé en janvier : dès que l'enseignant dépose un document dans son collecticiel ou dans un collecticiel partagé, une demande de commentaire est automatiquement adressé, ce qui ne devrait pas être le cas

**Comment by ericvincenterv** [comment]
ok, compris.

**Comment by ericvincenterv** [comment]
Première ligne : avant la modification
Seconde ligne : après la modification

![validation](https://cloud.githubusercontent.com/assets/5363344/13390388/543d7140-dece-11e5-856c-3624a17d0b34.png)

**Comment by jj-quintin** [comment]
Parfait
