### ISSUE TITLE
Rédiger un texte : comportement du texte par défaut dans champ texte

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#269]
Le texte par défaut "Votre texte ici" doit se comporter de la même manière que le titre : dès la saisie d'un caractère, le texte "Votre texte ici" s'efface 

![image](https://cloud.githubusercontent.com/assets/16414632/13117799/af962798-d5a1-11e5-89bd-6e07698ce3c6.png)

**Comment by purplefish32** [comment]
This issue was moved to claroline/ClaroSupport#9
