### ISSUE TITLE
Enseignant-accusé de réception-réversibilité des AR : "!"

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#270]
Dans la situation ci-dessous, j'ai sélectionné tous les documents et j'ai transmis pour tous un AR "Document bien reçu" (ça a bien marché). La réversibilité aussi fonctionne bien : j'ai remis les deux premier document à "Pas d'accusé de réception" (ok on le voit) et pour le 3ème, j'ai mis "Doublon" et cela fonctionne aussi. Mais le "!" doit en tenir compte et doit indiquer ici "2 opérations en attente" Tu vois le principe ?

![image](https://cloud.githubusercontent.com/assets/16414632/13118209/7f963284-d5a3-11e5-8585-bdfbd0ab69a2.png)

**Comment by ericvincenterv** [comment]
Compris. Je tente de reproduire en local.

**Comment by ericvincenterv** [comment]
@jj-quintin : 
En local, je n'ai pas réussi à reproduire.
Par contre, je suis allé sur ton espace http://demo-v6.innovalangues.net/innovacollecticielbundle/25/drops/awaiting et alors qu'il y a 11 documents, le "!" affiche "12 opérations en attente".

**Comment by jj-quintin** [comment]
A creuser donc

**Comment by jj-quintin** [comment]
C'est donc réglé ?

**Comment by ericvincenterv** [comment]
Logiquement, oui.

**Comment by jj-quintin** [comment]
Peux-tu tester à nouveau ?

Tu mets toutes les demandes (AR à la volée donc) sur "document bien reçu)
! doit donc disparaître
Tu en modifies l'une ou l'autre avec une valeur = document illisible par exemple
! doit réapparaître avec une valeur = au nombre en question

**Comment by ericvincenterv** [comment]
Je reste ce matin.

**Comment by ericvincenterv** [comment]
J'ai retesté, c'est bon en local.

**Comment by jj-quintin** [comment]
ok (on vérifiera une dernière fois après nouvelle mise en production, ok ?)

**Comment by ericvincenterv** [comment]
ok
