### ISSUE TITLE
AR : couleur des valeur d'AR dans la colonne des AR

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#271]
Je pense qu'il est préférable que les valeurs d'AR soient en noir (mêmes si elles sont activables, tant pis) et les icônes "Accuser la réception" en bleu. Ceci pour que l'on voit mieux la différences entre ce qui est fait (valeur d'AR différent de "Pas d'accusé de réception) et le reste. je suis bien conscient que ceci déroge à la règle générale (ce qui est activable est en bleu) mais je pense quand meêl que c'est mieux

Dans la vue ci-dessous, donc, afficher les icônes des deux premiers en bleu (la main index vers la droite) et les autres en noir
- 

![image](https://cloud.githubusercontent.com/assets/16414632/13118536/e17146f0-d5a4-11e5-94c1-d6d29872bdc8.png)

**Comment by ericvincenterv** [comment]
Résultat obtenu : 

![capture d ecran - 18022016 - 11 42 54](https://cloud.githubusercontent.com/assets/5363344/13140868/c7fa2558-d634-11e5-9047-2b371e16259d.png)

**Comment by jj-quintin** [comment]
ok
