### ISSUE TITLE
Rédiger un texte : le titre de la ressource texte elle-même

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#272]
Lors de la rédaction d'un texte, on a fait évoluer les choses pour avoir à la fois un titre et un contenu de texte (ce n'était pas prévu ainsi dans la bundle d'origine développé par Lyon dans lequel on n'avait que du texte). Cette rédaction génère en réalité une ressource "texte" dont le titre est toujours "Texte" (ou "Texte~x" si plusieurs Textes et le contenu, celui indiqué dans le corps du texte. Il faudrait que le titre du texte soit celui indiqué par l'utilisateur

![image](https://cloud.githubusercontent.com/assets/16414632/13119073/811ba00e-d5a7-11e5-9f34-afc19b41386e.png)

donne ceci, en lecture :  

![image](https://cloud.githubusercontent.com/assets/16414632/13119102/9cd0e11a-d5a7-11e5-86a7-69d9884583a2.png)

**Comment by ericvincenterv** [comment]
Note : il faut modifier la gestion des fichiers cachés car Claroline affiche à partir de cet endroit.

**Comment by ericvincenterv** [comment]
Voici le résultat : 

quand nous regardons dans les fichiers cachés, maintenant nous voyons le titre saisi et non plus "text~" (voir les 3 cas de droite)
![capture d ecran - 18022016 - 11 23 08](https://cloud.githubusercontent.com/assets/5363344/13140388/1821e6f4-d632-11e5-80e5-4038c2db0c40.png)

quand nous regardons la ressource, maintenant nous voyons le titre saisi et non plus "text~"
![capture d ecran - 18022016 - 11 23 19](https://cloud.githubusercontent.com/assets/5363344/13140382/12264a10-d632-11e5-9e60-250be6541a63.png)

**Comment by jj-quintin** [comment]
Parfait
