### ISSUE TITLE
Paramètres - Fermer le collecticiel : texte du message d'alerte

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#273]
Modifier le texte ci-dessous : 
![image](https://cloud.githubusercontent.com/assets/16414632/13119171/026c0400-d5a8-11e5-96b6-87d113e0f526.png)

Par

Fermeture du collecticiel

Voulez-vous fermer le collecticiel ?

i : le texte de l'info est ok :-)

**Comment by ericvincenterv** [comment]
Le résultat : 
![capture d ecran - 18022016 - 09 40 21](https://cloud.githubusercontent.com/assets/5363344/13137816/ac8224d0-d623-11e5-90a1-a6cd67a9a03c.png)

**Comment by jj-quintin** [comment]
ok
