### ISSUE TITLE
Fermer le collecticiel : affichage du message sous fond jaune

### ISSUE THREAD

**Issue by jj-quintin** [InnovaLangues/CollecticielBundle#274]
Ok sauf dans le cas où le bouton "Action" est présent
Le mieux probablement (et le plus simple) est d'afficher le message d'avertissement en question plus haut (tout en en haut à droite du fond blanc (tu vois ?)

![image](https://cloud.githubusercontent.com/assets/16414632/13119344/f4649b14-d5a8-11e5-91ab-67c105819a32.png)

**Comment by ericvincenterv** [comment]
Ok, compris.

**Comment by ericvincenterv** [comment]
@jj-quintin : est-ce que ce positionnement est correct ?

![capture d ecran - 18022016 - 09 57 29](https://cloud.githubusercontent.com/assets/5363344/13138213/0fdc5e04-d626-11e5-8c15-52d25d7df0df.png)

**Comment by jj-quintin** [comment]
Parfait
