### ISSUE TITLE
Libellé à côté de la case à cocher "Valider le document"

### ISSUE THREAD

**Issue by purplefish32** [InnovaLangues/CollecticielBundle#32]
A coté de  la case a cocher "Valider le document" on affiche "Demande transmise" lors de la validation du document.

**Comment by ericvincenterv** [comment]
L'affichage est fait lorsqu'une demande est déjà transmise.
Par contre, lors de la demande de commentaire, la zone "demande transmise" ne s'affiche pas.
Reste donc à faire la partie "Ajax".

**Comment by ericvincenterv** [comment]
Fait avec l'aide d'Arnaud. Merci ;-)
