### ISSUE TITLE
Titre la modal de création d'une nouvelle ressource de type collecticiel

### ISSUE THREAD

**Issue by purplefish32** [InnovaLangues/CollecticielBundle#35]
Dans la modal de création d'une nouvelle ressource de type collecticiel, changer le titre en "Créer un collecticiel" et le libellé du champ "Titre"

**Comment by ericvincenterv** [comment]
Lors de la création d'une ressource, on a ceci : 
![ressource-fichier](https://cloud.githubusercontent.com/assets/5363344/8325748/22d2b7d2-1a5c-11e5-8109-7495bf2eff2b.png)
![ressource-repertoire](https://cloud.githubusercontent.com/assets/5363344/8325753/2af5e916-1a5c-11e5-8583-34c09bd604bb.png)

Donc, on a toujours : 
"Créer une nouvelle ressource" puis entre parenthèses le nom du type de la ressource.
Donc, nous ne pouvons pas mettre : "Créer un collecticiel"

Nous obtenons ceci : 
![ressource-collecticiel](https://cloud.githubusercontent.com/assets/5363344/8325794/6ead3826-1a5c-11e5-9667-2386ba08186f.png)

Est-ce correct ?
