### ISSUE TITLE
Vue enseignant : onglet 'Espace partagés'

### ISSUE THREAD

**Issue by purplefish32** [InnovaLangues/CollecticielBundle#38]
Ajouter un onglet "Espace partagés" intercalé entre entre "Demandes adressées" et "Paramètres".

On retrouve la liste (tableau) de tous les collecticiels (idem à ce qu'on a aujourd’hui sous l'onglet "Demandes adressées")

**Comment by ericvincenterv** [comment]
Ajout de l'onglet effectué. Voir pour le contenu.

**Comment by ericvincenterv** [comment]
Voici pour le contenu de cet onglet : 

![onglet espace partages](https://cloud.githubusercontent.com/assets/5363344/8431854/7df57a5c-1f3c-11e5-9d27-7f73f01b709e.png)

Cet onglet était prévu pour la V2. A voir si on a le temps.

**Comment by ericvincenterv** [comment]
Vue maintenant OK. Reste à faire les calculs.
