### ISSUE TITLE
Vue enseignant : onglet 'Demandes adressées'

### ISSUE THREAD

**Issue by purplefish32** [InnovaLangues/CollecticielBundle#40]
Le tableau dans l'onglet "demandes adressés" sera modifié

Le tableau est une liste de **documents** et pas de collecticiels. Trié par date de dépôt de document.
Un doute subsiste sur le libellé : "demande transmise" ou "demandes adressés".

Jean-Jaques fournira un document plus complet sur les colonnes du tableau.

**Comment by ericvincenterv** [comment]
Jean-Jacques souhaite ceci : 

![demandes-adresses](https://cloud.githubusercontent.com/assets/5363344/8408500/e99a8256-1e70-11e5-8a1d-b2bb7b04eadf.png)

**Comment by ericvincenterv** [comment]
Suite et fin du document : 
![demandes-2](https://cloud.githubusercontent.com/assets/5363344/8408521/1269f1da-1e71-11e5-93a6-0f431ad6884b.png)

**Comment by ericvincenterv** [comment]
Vue maintenant OK. Reste à faire les calculs.
