### ISSUE TITLE
Faire la liste intéractive des messages

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#8]
Il pourra être possible d'insérer un commentaire après un commentaire et pas forcément après la liste.

Ceci modifiera le schéma de la base de données et des traitements.

**Comment by ericvincenterv** [comment]
Pour les versions 1.*, ce fonctionnement est resté. Il doit évaluer dans la version 2.

**Comment by ericvincenterv** [comment]
Prévoir de pouvoir supprimer et modifier un commentaire à partir de la liste des commentaires.

**Comment by ericvincenterv** [comment]
Vu avec Donovan : voir avec JJQ.

**Comment by purplefish32** [comment]
This issue was moved to claroline/Claroline#735
