### ISSUE TITLE
Changer les options de la ressource

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#84]
Dans la liste des collectiels, il faut enlever les 3 ou 4 dernières possibilités.

Et dans l'édition des propriétés, il faut modifier le type en "Collecticiel".

**Comment by ericvincenterv** [comment]
A revoir pour la prochaine version.

**Comment by ericvincenterv** [comment]
Vu avec Donovan : 
voir avec JJQ car il est l'initiateur.

**Comment by purplefish32** [comment]
This issue was moved to claroline/Claroline#765
