### ISSUE TITLE
Modifier le fonctionnement des fichiers cachés

### ISSUE THREAD

**Issue by ericvincenterv** [InnovaLangues/CollecticielBundle#85]
Les fichiers/répertoires cachés s'affichent au même niveau que la liste des collecticiels.

Ceci est à revoir.

**Comment by ericvincenterv** [comment]
A voir pour la version 2 ?

**Comment by ericvincenterv** [comment]
Vu avec Donovan : stand-by.

**Comment by purplefish32** [comment]
This issue was moved to claroline/Claroline#764
